### ISSUE TITLE
Allow big inputs

### ISSUE THREAD

**Issue by igorsnunes** [PPC64/sha2-le#1]
Big inputs (bigger than 3mb) are not allowed by the OS (probably because we are using static vector allocation).

**Comment by gut** [comment]
please check mmap branch on d7132633d8108c9ee7aafb2c70cf5263559aa4ef

**Comment by racardoso** [comment]
This kind of allocation wont work with huge sizes https://github.com/PPC64/sha2-le/blob/master/sha2.h#L228 replace this with `malloc` should work.  A `mmap` also work.

**Comment by racardoso** [comment]
I change to a malloc https://github.com/PPC64/sha2-le/commit/746a4541d0f7cc807fad79b70f723944f6ba6e59 and works we could change it to mmap. Even better may we can use a `calloc` instead  as it zeros memory so we may do not need a the for to iterate and fill zeros https://github.com/PPC64/sha2-le/blob/master/sha2.h#L154

**Comment by racardoso** [comment]
I'll close this issue as it is solved. We can discuss mmap vs malloc in another thread if we need.
