### ISSUE TITLE
Investigate efficiency of gcc builtin sigma functions and analyse generated code

### ISSUE THREAD

**Issue by gut** [PPC64/sha2-le#3]
Functions like `__builtin_crypto_vshasigmaw` can be used directly by gdb. By looking at the output with -O3 it may give us better insight of how to best develop this functionality for ppc64le on other projects.

**Comment by racardoso** [comment]
I do some little changes on this code ad50124cc25a22edad71560d2bd04a8723d160e6  It's a optimization idea. Since I'll have to check any performance issues with this optimization candidate we can work together on this issue.

**Comment by brunoalr** [comment]
Closing this issue since we killed everything except for the asm versions.
