### ISSUE TITLE
Undefined behavior in tests.c

### ISSUE THREAD

**Issue by brunoalr** [PPC64/sha2-le#5]
When compiling with sanitizer flags `-fsanitize=address,undefined` the following errors are displayed:

<pre>
tests.c:28:5: runtime error: left shift of 134217728 by 30 places cannot be represented in type 'int'
tests.c:28:5: runtime error: left shift of 134217728 by 19 places cannot be represented in type 'int'
tests.c:28:5: runtime error: left shift of 134217728 by 10 places cannot be represented in type 'int'
tests.c:29:8: runtime error: left shift of 134217728 by 26 places cannot be represented in type 'int'
tests.c:29:8: runtime error: left shift of 134217728 by 21 places cannot be represented in type 'int'
tests.c:29:8: runtime error: left shift of 134217728 by 7 places cannot be represented in type 'int'
./bin/test256_ll_intrinsics
./bin/test256_ll_asm
./bin/test512
tests.c:63:5: runtime error: shift exponent 63 is too large for 32-bit type 'int'
tests.c:63:5: runtime error: shift exponent 56 is too large for 32-bit type 'int'
tests.c:64:8: runtime error: left shift of 4611686018427387904 by 45 places cannot be represented in type 'long int'
tests.c:64:8: runtime error: left shift of 4611686018427387904 by 3 places cannot be represented in type 'long int'
tests.c:65:5: runtime error: left shift of 4611686018427387904 by 36 places cannot be represented in type 'long int'
tests.c:65:5: runtime error: left shift of 4611686018427387904 by 30 places cannot be represented in type 'long int'
tests.c:65:5: runtime error: left shift of 4611686018427387904 by 25 places cannot be represented in type 'long int'
tests.c:66:5: runtime error: left shift of 4611686018427387904 by 50 places cannot be represented in type 'long int'
tests.c:66:5: runtime error: left shift of 4611686018427387904 by 46 places cannot be represented in type 'long int'
tests.c:66:5: runtime error: left shift of 4611686018427387904 by 23 places cannot be represented in type 'long int'
</pre>

**Comment by racardoso** [comment]
We pass constants to a macro. When suffix (like U, UL, LL) are not used, the compiler uses the first type   that can contains the constant. Since the constants  'fits' on int and long int hence, we got 'cannot  
be represented' errors because some shifts overflow those (signed) types. Use unsigned types instead. In fact there's no use case for signed int on sha2 algorithm. Close via f1fd0a9901693df16b0406f593514e405099b491
